spring:
  profiles:
    active: native #use native filesystem config by default instead of git. REVISIT.
  config.server.native.searchLocations: ${config.path:file:./config}

logging:
  level:
    root: WARN
    o.s.c.c.s.e.NativeEnvironmentRepository: WARN