geoserver:
  web-ui:
    # Theese are all default values, here just for reference. You can omit them and add only the ones to disable or further configure
    security.enabled: true
    wfs.enabled: true
    wms.enabled: true
    wcs.enabled: true
    wps.enabled: false # not working yet
    gwc.enabled: false # not ready yet
    extensions:
      importer.enabled: true
    demos:
      enabled: true
      wps-request-builder: true
      wcs-request-builder: true
      demo-requests: true
      srs-list: true
      reprojection-console: true
      layer-preview-page:
        enabled: true
        common-formats:
          open-layers: true
          gml: true
          kml: false #kml links are broken
    tools:
      enabled: true
      resource-browser: true
      catalog-bulk-load: true
