version: "3.8"

volumes:
  acl_data:

services:
  acldb:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: acl
      POSTGRES_USER: acl
      POSTGRES_PASSWORD: acls3cr3t
    networks:
      - gs-cloud-network
    volumes:
      - acl_data:/var/lib/postgresql/data
    ports:
      - 6432:5432
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G

  acl:
    image: geoservercloud/geoserver-acl:1.0.0
    volumes:
      - ../config/acl-service.yml:/opt/app/bin/acl.yml
    depends_on:
      - acldb
    environment:
      GEOSERVER_BASE_PATH: ${GATEWAY_BASE_PATH}
    networks:
      - gs-cloud-network
    ports:
      - 9000:8080
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
