version: "3.8"

volumes:
  pgconfigdb_data: # volume for postgresql data, used to store the geoserver config through jdbcconfig

#
# Configures all geoserver services to use the postgresql database server with jdbcconfig as catalog backend.
# Run with `docker-compose --compatibility -f docker-compose.yml -f docker-compose-jdbcconfig.yml up -d`
#
services:
  pgconfigdb:
    image: postgres:15
    shm_size: 2g
    environment:
      POSTGRES_DB: pgconfig
      POSTGRES_USER: pgconfig
      POSTGRES_PASSWORD: pgconfig
    ports:
      - 54322:5432
    networks:
      - gs-cloud-network
    volumes:
      - pgconfigdb_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G

  wfs:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},pgconfig"
    depends_on:
      - pgconfigdb

  wms:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},pgconfig"
    depends_on:
      - pgconfigdb

  wcs:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},pgconfig"
    depends_on:
      - pgconfigdb

  rest:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},pgconfig"
    depends_on:
      - pgconfigdb

  webui:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},pgconfig"
    depends_on:
      - pgconfigdb

  gwc:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},pgconfig"
    depends_on:
      - pgconfigdb

  wps:
    environment:
      SPRING_PROFILES_ACTIVE: "${DEFAULT_PROFILES},pgconfig"
    depends_on:
      - pgconfigdb
